# config/config.yaml
fhe:
  poly_modulus_degree: 32768  
  coeff_mod_bit_sizes: [60, 40, 40, 40, 60, 60]
  global_scale: 1099511627776

training:
  num_clients: 3
  num_rounds: 5
  local_epochs: 4
  lr: 0.01
  min_clients: 3

privacy:
  dp_sigma: 0.5  # Noise multiplier
  dp_clip: 1.0    # Gradient clipping bound

logging:
  file: /fhe-fl/fl_logs.log  # This shows the filename